// Import all command modules to trigger registerCommand() side effects
import './shared/logout.js'
import './shared/clear.js'
import './shared/exit.js'
import './shared/help.js'
import './shared/packages.js'
import './admin/login-admin.js'
import './admin/devices.js'
import './admin/quota.js'
import './admin/tokens.js'
import './client/login.js'
import './client/me.js'
import './client/connect.js'
import './client/disconnect.js'
import './client/send.js'
import './client/webhook.js'
import './client/contact.js'
